const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require(path.join(process.env.TUBESHELF_NODE_MODULES,'playwright'));
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'en-US'});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.route('https://i.ytimg.com/**',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#302858"/><circle cx="320" cy="180" r="95" fill="#7760ce"/><path d="M300 140L360 180L300 220Z" fill="white"/></svg>'}));
 try {
  await page.goto('http://127.0.0.1:8766/extension/dashboard/dashboard.html?lang=en');
  await page.locator('[data-group="learning"]').click();
  assert.equal(await page.locator('.member-toggle').count(),0);
  await page.locator('#manage-members').click();
  await page.locator('[data-member="/@kurzgesagt"]').uncheck();
  await page.locator('#search').fill('Lofi');
  await page.locator('#add-filtered').click();
  assert.equal(await page.locator('[data-group="learning"] .group-number').textContent(),'2');
  await page.locator('#cancel-members').click();
  assert.equal(await page.locator('[data-group="learning"] .group-number').textContent(),'2');
  await page.locator('#manage-members').click();
  await page.locator('[data-member="/@kurzgesagt"]').uncheck();
  await page.locator('[data-member="/@lofigirl"]').check();
  await page.screenshot({path:'work/member-editor-en.png',fullPage:true});
  await page.locator('#save-members').click();
  await page.locator('#member-manager').waitFor({state:'hidden'});
  await page.locator('#search').fill('');
  assert.equal(await page.locator('[data-channel-row="/@kurzgesagt"]').count(),0);
  assert.equal(await page.locator('[data-channel-row="/@lofigirl"]').count(),1);
  await page.locator('[data-detail="/@lofigirl"]').click();
  await page.locator('#channel-dialog').waitFor({state:'visible'});
  await page.locator('#detail-close').click();
  await page.goto('http://127.0.0.1:8766/extension/dashboard/dashboard.html?lang=zh-TW');
  await page.locator('[data-group="learning"]').click();
  await page.locator('#manage-members').click();
  await page.locator('[data-member="/@lofigirl"]').check();
  await page.screenshot({path:'work/member-editor-zh.png',fullPage:true});
  await page.locator('#cancel-members').click();

  const fixture='http://127.0.0.1:8766/tests/favorites-harness.html';
  await page.goto(fixture);
  const entry=page.locator('[data-ts-action="favorites"]');
  await entry.waitFor();
  assert.equal(await entry.evaluate(button=>button.parentElement.nextElementSibling.className),'ts-guide-heading');
  assert.equal(await page.locator('.ts-favorite-entry button').count(),1);
  await entry.click();
  await page.locator('#tubeshelf-favorites-page').waitFor();
  assert.equal(await page.locator('#native-feed').isVisible(),false);
  assert.equal(await page.locator('#tubeshelf-toolbar').isVisible(),false);
  await page.locator('.ts-favorite-heading [data-favorite-action="manage"]').click();
  await page.locator('dialog select').selectOption('group:learning');
  assert.equal(await page.locator('[data-favorite-toggle]').count(),1);
  await page.locator('[data-favorite-toggle="/@science"]').click();
  await page.waitForFunction(()=>__state().favoriteChannelIds.includes('/@science'));
  await page.locator('dialog select').selectOption('');
  await page.locator('dialog input[type=search]').fill('Design');
  assert.equal(await page.locator('[data-favorite-toggle]').count(),1);
  await page.locator('[data-favorite-toggle="/@design"]').click();
  await page.locator('dialog input[type=search]').fill('');
  await page.locator('[data-favorite-toggle="/@empty"]').click();
  await page.locator('[data-favorite-action="close"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.ts-favorite-video').length===3);
  await page.locator('[data-favorite-retry="/@design"]').waitFor();
  assert.equal(await page.locator('.ts-favorite-video').first().getAttribute('href'),'https://www.youtube.com/watch?v=science0003');
  await page.waitForFunction(()=>document.querySelector('.ts-favorite-feed').innerText.includes('No public videos available'));
  assert.deepEqual(await page.evaluate(()=>__state().groups[0].channelIds),['/@science']);
  await page.evaluate(()=>{__failDesign=false;});
  await page.locator('[data-favorite-retry="/@design"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.ts-favorite-video').length===6);
  await page.locator('[data-favorite-action="refresh"]').click();
  await page.waitForFunction(()=>!document.querySelector('[data-favorite-action="refresh"]').disabled);
  assert.ok((await page.evaluate(()=>__feedCalls.slice(-3))).every(call=>call.force));
  await page.screenshot({path:'work/favorites-en-light.png',fullPage:true});
  await page.evaluate(()=>{document.documentElement.setAttribute('dark','');const next=structuredClone(__state());next.settings.language='zh-TW';next.revision++;__change(next);});
  assert.equal(await page.locator('.ts-favorite-heading h1').innerText(),'最關注頻道');
  await page.screenshot({path:'work/favorites-zh-dark.png',fullPage:true});
  await page.locator('.ts-favorite-heading [data-favorite-action="manage"]').click();
  await page.screenshot({path:'work/favorites-picker-zh.png',fullPage:true});
  await page.evaluate(()=>{__failSave=true;});
  await page.locator('[data-favorite-toggle="/@music"]').click();
  await page.waitForFunction(()=>document.querySelector('.ts-favorite-picker-error').textContent.length>0);
  assert.equal(await page.locator('dialog').isVisible(),true);
  assert.equal(await page.locator('[data-favorite-toggle="/@music"]').getAttribute('aria-pressed'),'false');
  assert.equal(await page.evaluate(()=>__state().favoriteChannelIds.includes('/@music')),false);
  await page.evaluate(()=>{__failSave=false;});
  await page.locator('[data-favorite-toggle="/@music"]').click();
  await page.waitForFunction(()=>__state().favoriteChannelIds.includes('/@music'));
  await page.locator('[data-favorite-action="close"]').click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('[data-favorite-remove="/@music"]').click();
  await page.waitForFunction(()=>!__state().favoriteChannelIds.includes('/@music'));
  // Changing Shorts preference discards an in-flight RSS response and cached Shorts.
  await page.evaluate(()=>{__feedDelay=300;});
  await page.locator('[data-favorite-action="refresh"]').click();
  await page.evaluate(()=>{const next=structuredClone(__state());next.settings.hideShorts=true;next.revision++;__change(next);});
  await page.waitForFunction(()=>document.querySelectorAll('.ts-favorite-video').length===2);
  assert.ok((await page.locator('.ts-favorite-video strong').allTextContents()).every(title=>title==='Normal upload'));
  await page.evaluate(()=>{const next=structuredClone(__state());next.settings.hideShorts=false;next.revision++;__change(next);});
  await page.waitForFunction(()=>document.querySelectorAll('.ts-favorite-video').length===6);
  await page.goto(fixture+'#tubeshelf-view=favorites');
  await page.locator('#tubeshelf-favorites-page').waitFor();
  assert.equal((await page.evaluate(()=>__state().favoriteChannelIds)).length,3);
  await page.locator('[data-favorite-action="back"]').click();
  await page.locator('#tubeshelf-favorites-page').waitFor({state:'detached'});
  assert.equal(await page.locator('#native-feed').isVisible(),true);
  assert.equal(await page.locator('#tubeshelf-toolbar').isVisible(),true);
  await page.locator('[data-ts-action="favorites"]').click();
  await page.evaluate(()=>{const next=structuredClone(__state());next.settings.enabled=false;next.revision++;__change(next);});
  await page.locator('#tubeshelf-favorites-page').waitFor({state:'detached'});
  assert.equal(await page.locator('#native-feed').isVisible(),true);
  assert.equal((await page.evaluate(()=>__state().favoriteChannelIds)).length,3);
  await page.evaluate(()=>{const next=structuredClone(__state());next.settings.enabled=true;next.revision++;__change(next);});
  await page.locator('#tubeshelf-favorites-page').waitFor();
  assert.deepEqual(errors,[]);
  console.log('Favorites smoke passed: staged group edits, cancel/save, bilingual screenshots, favorite persistence, RSS date ordering, partial failure/retry, refresh, failed-save recovery, navigation and power cleanup.');
 } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
